apiVersion: templates.gatekeeper.sh/v1
kind: ConstraintTemplate
metadata:
  name: k8sdisallowlatesttag
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  crd:
    spec:
      names:
        kind: K8sDisallowLatestTag
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package k8sdisallowlatesttag

      violation[{"msg": msg}] {
        image := container_images[_]
        endswith(image, ":latest")
        msg := sprintf("image %q must not use the latest tag", [image])
      }

      container_images[image] {
        input.review.kind.kind == "Pod"
        container := input.review.object.spec.containers[_]
        image := container.image
      }

      container_images[image] {
        input.review.kind.kind != "Pod"
        container := input.review.object.spec.template.spec.containers[_]
        image := container.image
      }

